# Generated by Django 5.0.6 on 2024-05-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="brand",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
    ]
