# Generated by Django 5.0.6 on 2024-05-24 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_product_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
    ]
